spring:
  datasource:
    generate-unique-name: false
    name: questions
    url: jdbc:h2:mem:questions
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, info
  endpoint:
    health:
      probes:
        enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: Question Service
    description: Exposes end-points to get the questions
    owner: Beast Boy
