spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/UserService
            - classpath:/QuestionService
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'