spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KarthikReddyMaru/QZ-Properties.git
          clone-on-start: true
          default-label: test/config-props
          force-pull: true
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'