spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:users
    generate-unique-name: false
    name: users
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
