spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:users
    generate-unique-name: false
    name: users
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, info
  endpoint:
    health:
      probes:
        enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: User Service
    description: Allows users to register with QZ.
    owner: Beast Boy